spring:
  profiles:
    active: dev
  application:
    name: intelligent-teaching-system

server:
  port: 8080
  servlet:
    context-path: /api

mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.zhike.entity
  configuration:
    map-underscore-to-camel-case: true
